/**
 * Safety Level Definitions
 * Based on data lifecycle and recoverability principles
 */

export type SafetyLevel = 'safe' | 'caution' | 'danger';

export interface SafetyLevelDefinition {
  level: SafetyLevel;
  label: string;
  emoji: string;
  definition: string;
  criteria: string[];
  examples: string[];
  consequence: string;
}

/**
 * Scientific definitions based on:
 * 1. Data Recoverability - Can the data be regenerated automatically?
 * 2. User Value - Does the data contain user decisions/inputs?
 * 3. Functional Dependency - Does the software depend on this data?
 */
export const SAFETY_DEFINITIONS: Record<SafetyLevel, SafetyLevelDefinition> = {
  safe: {
    level: 'safe',
    label: 'Safe',
    emoji: '✓',
    definition: 'Temporary data that can be safely deleted without functional impact.',
    criteria: [
      'Auto-generated by the system',
      'Can be regenerated on next use',
      'No user-created content',
      'Deletion does not affect core functionality'
    ],
    examples: ['cache/', 'debug/', 'logs/', 'telemetry/', 'temp/'],
    consequence: 'The application will regenerate this data automatically when needed.'
  },
  caution: {
    level: 'caution',
    label: 'Caution',
    emoji: '⚠',
    definition: 'Data with potential user value that may be difficult to recover.',
    criteria: [
      'May contain user preferences or history',
      'Could include work-in-progress items',
      'Not critical for functionality',
      'Recovery may require manual effort'
    ],
    examples: ['history/', 'conversations/', 'projects/', 'todos/'],
    consequence: 'You may lose conversation history, preferences, or work-in-progress items.'
  },
  danger: {
    level: 'danger',
    label: 'Danger',
    emoji: '✕',
    definition: 'Critical data essential for application functionality.',
    criteria: [
      'Required for the application to function',
      'Contains installed extensions or plugins',
      'Stores authentication or configuration',
      'Cannot be automatically regenerated'
    ],
    examples: ['plugins/', 'extensions/', 'config/', 'credentials/'],
    consequence: 'The application may malfunction or require reinstallation. Features may stop working.'
  }
};

/**
 * Get tooltip content for a safety level
 */
export function getSafetyTooltip(level: SafetyLevel): string {
  const def = SAFETY_DEFINITIONS[level];
  return [
    `${def.emoji} ${def.label.toUpperCase()}`,
    '',
    `Definition: ${def.definition}`,
    '',
    'Criteria:',
    ...def.criteria.map(c => `  • ${c}`),
    '',
    `Examples: ${def.examples.join(', ')}`
  ].join('\n');
}

/**
 * Get warning message when changing safety level
 */
export function getLevelChangeWarning(
  fromLevel: SafetyLevel,
  toLevel: SafetyLevel,
  dirName: string
): { title: string; message: string } | null {
  // Only warn when making something more deletable (less safe)
  const riskOrder: SafetyLevel[] = ['danger', 'caution', 'safe'];
  const fromRisk = riskOrder.indexOf(fromLevel);
  const toRisk = riskOrder.indexOf(toLevel);

  if (toRisk > fromRisk) {
    // Moving to a less safe level (more deletable)
    const toDef = SAFETY_DEFINITIONS[toLevel];
    return {
      title: `Change "${dirName}" to ${toDef.label}?`,
      message: `Warning: Changing from ${SAFETY_DEFINITIONS[fromLevel].label} to ${toDef.label} ` +
        `will allow this directory to be deleted more easily.\n\n` +
        `Consequence if deleted:\n${toDef.consequence}\n\n` +
        `Are you sure you want to proceed?`
    };
  }

  if (fromRisk > toRisk) {
    // Moving to a safer level (less deletable) - this is fine, just confirm
    return {
      title: `Change "${dirName}" to ${SAFETY_DEFINITIONS[toLevel].label}?`,
      message: `This will add more protection to this directory.`
    };
  }

  return null; // Same level, no warning needed
}

/**
 * Format safety level for display
 */
export function formatSafetyBadge(level: SafetyLevel): string {
  const def = SAFETY_DEFINITIONS[level];
  return `${def.emoji} ${def.label}`;
}
